CREATE TABLE "account" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hashed" varchar(255) NOT NULL,
  "user_type" smallint NOT NULL,
  "is_2fa_enabled" bool NOT NULL DEFAULT (false),
  "totp_secret_encrypted" varchar,
  "passkey_enabled" bool NOT NULL DEFAULT (false),
  "is_blocked" bool NOT NULL DEFAULT (false),
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "totp_backup_code" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "code_hashed" varchar NOT NULL,
  "is_used" bool NOT NULL DEFAULT (false),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "user_profile" (
  "user_id" bigint PRIMARY KEY NOT NULL,
  "basic_info" JSONB,
  "education" JSONB,
  "academic" JSONB,
  "test" JSONB,
  "internship" JSONB,
  "project" JSONB,
  "campus" JSONB,
  "award" JSONB,
  "liked_university" JSONB,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "refresh_token" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" bigint NOT NULL,
  "token_hashed" varchar(500) NOT NULL,
  "user_agent" varchar(100) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "expire_at" timestamptz NOT NULL DEFAULT (now() + interval '30 days')
);

CREATE TABLE "passkey" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "credential_id" text UNIQUE NOT NULL,
  "public_key" text NOT NULL,
  "sign_count" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "last_used_at" timestamptz NOT NULL DEFAULT (now()),
  "is_active" bool NOT NULL DEFAULT (true)
);

CREATE INDEX ON "totp_backup_code" ("user_id", "is_used");

CREATE UNIQUE INDEX ON "refresh_token" ("token_hashed");

CREATE INDEX ON "refresh_token" ("user_id");

CREATE INDEX ON "refresh_token" ("expire_at");

CREATE UNIQUE INDEX ON "passkey" ("user_id", "credential_id");

CREATE INDEX ON "passkey" ("user_id", "is_active");

COMMENT ON COLUMN "account"."email" IS 'Emails are all in small cases';

COMMENT ON COLUMN "account"."totp_secret_encrypted" IS 'use AES-GCM to encrypt, `not null` if 2FA is enabled';

COMMENT ON COLUMN "account"."updated_at" IS 'Auto-updated via trigger on UPDATE';

COMMENT ON COLUMN "user_profile"."updated_at" IS 'Auto-updated via trigger on UPDATE';

COMMENT ON TABLE "refresh_token" IS 'Used as session store to validate login state by token';

ALTER TABLE "user_profile" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "refresh_token" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "totp_backup_code" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;

ALTER TABLE "passkey" ADD FOREIGN KEY ("user_id") REFERENCES "account" ("user_id") ON DELETE CASCADE;
